dist: bionic
language: python
addons:
  apt:
    packages:
      - libgeoip-dev
matrix:
  include:
    - name: “Python 2.7 on xenial”
      python: "2.7"
      dist: xenial
    - name: “Python 2.7 on bionic”
      python: "2.7"
    - name: “Python 3.8 on bionic”
      python: "3.8"
  allow_failures:
    - python: "3.8"
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  # if Travis is running Python 3, then
  #   refresh the git submodule ./vendor/acs4_py
  #   refresh the git submodule ./vendor/infogami
  #   git commit those changes into this pull request
  #   TODO: flake8 ./vendor --select=E9,F63,F7,F82 to unsure new versions pass
  #   create a legacy Python for npm/node until nodejs/node#25789 is resolved
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then
      pushd vendor/infogami && git pull origin master && popd;
      git status;
      git commit -am"Update git submodules in .vendor";
      pyenv install 2.7.14;
    fi
  - npm install
script: make test
